version: '3'
services:
  lcon:
    build: 
      context: ./lcon.Dockerfile
    image: lcon
    ports:
      - "8000:8000"

  server1:
    build: 
      context: ../server/server.Dockerfile
    image: server
    ports:
      - "8080:8080"

  server2:
    build: 
      context: ../server/server.Dockerfile
    image: server
    ports:
      - "8081:8080"

  server3:
    build: 
      context: ../server/server.Dockerfile
    image: server
    ports:
      - "8082:8080"