name: Build and Publish Docker Images

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image - http_server
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: ./go/server/server.Dockerfile
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/http_server:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/http_server:latest
          platforms: linux/amd64,linux/arm64

      - name: Build and push Docker image - round_robin
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: ./go/rr/rr.Dockerfile
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/rr:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/rr:latest
          platforms: linux/amd64,linux/arm64

      - name: Build and push Docker image - weighted_round_robin
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: ./go/wrr/wrr.Dockerfile
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/wrr:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/wrr:latest
          platforms: linux/amd64,linux/arm64


      - name: Build and push Docker image - least_connections
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: ./go/lcon/lcon.Dockerfile
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/least_connections:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/least_connections:latest
          platforms: linux/amd64,linux/arm64

      - name: Build and push Docker image - random
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: ./go/random/random.Dockerfile
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/random:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/random:latest
          platforms: linux/amd64,linux/arm64