name: Build and Publish Docker Images

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image - lb
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: lb.Dockerfile
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/lb:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/lb:latest
          platforms: linux/amd64,linux/arm64

      - name: Build and push Docker image - iperf3_server
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: server.Dockerfile
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/server:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/server:latest
          platforms: linux/amd64,linux/arm64

      - name: Build and push Docker image - iperf3_client
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: client.Dockerfile
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/client:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/client:latest
          platforms: linux/amd64,linux/arm64